services:
  # SERVIDOR (EL CEREBRO)
  - type: web
    name: lidIA-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: GROQ_API_KEY
        fromLink:
          type: variable
          name: GROQ_API_KEY

  # LA APP (LA CARA)
  - type: static
    name: lidIA-app-premium
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://lidia-backend.onrender.com